src/AppBundle/Entity/Author.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Author
 *
 * @ORM\Table(name="author")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\AuthorRepository")
 */
class Author
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="author_name", type="string", length=255)
     */
    private $AuthorName;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birth_date", type="date")
     */
    private $birthDate;

     /**
      * @var int
      * @ORM\ManyToOne(targetEntity="Country")
      * @ORM\JoinColumn(name="country_id", referencedColumnName="id")
      */
     private $country;

     /**
      * @ORM\ManyToMany(targetEntity="Book", mappedBy="authors", cascade={"persist"})
      */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    /**
     * Get the value of Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Id
     *
     * @param int id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of Author Name
     *
     * @return string
     */
    public function getAuthorName()
    {
        return $this->AuthorName;
    }

    /**
     * Set the value of Author Name
     *
     * @param string AuthorName
     *
     * @return self
     */
    public function setAuthorName($AuthorName)
    {
        $this->AuthorName = $AuthorName;

        return $this;
    }

    /**
     * Get the value of Birth Date
     *
     * @return \DateTime
     */
    public function getBirthDate()
    {
        return $this->birthDate;
    }

    /**
     * Set the value of Birth Date
     *
     * @param \DateTime birthDate
     *
     * @return self
     */
    public function setBirthDate(\DateTime $birthDate)
    {
        $this->birthDate = $birthDate;

        return $this;
    }


    /**
     * Get the value of Country
     *
     * @return int
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set the value of Country
     *
     * @param int country
     *
     * @return self
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }


    public function addBook(Book $book): self
    {
        $this->books[] = $book;

        return $this;
    }

    public function removeBook(Book $book): bool
    {
        return $this->books->removeElement($book);
    }

    public function getBooks(): Collection
    {
        return $this->books;
    }

}

src/AppBundle/Resources/views/Admin/authors.html.twig
{% extends 'adminBase.html.twig' %}

{% block body %}
  {% include '/Navbar/adminNavbar.html.twig' %}

  <div id="wrapper">
    {% include '/Sidebar/adminSidebar.html.twig' %}
    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>



        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Authors</div>
          <div class="card-body">
            <button type="button" class="btn btn-outline-danger mb-3 disabled" style="width:5%" id="bremove" name="authors">Remove</button>
            <button type="button" class="btn btn-outline-info mb-3 disabled" style="width:5%" id="bedit" name="authors">Edit</button>
            <table class="table table-bordered" id="tabela" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Author Name</th>
                  <th>Country</th>
                </tr>
              </thead>

              <tbody>
                {% for author in authors %}
                  <tr id="{{ author.authorId }}">
                    <td>{{ author.authorName}}</td>
                    <td>{{ author.country}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Books App 2018</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ path('logout') }}">Logout</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

src/AppBundle/Resources/views/Admin/books.html.twig
{% extends 'adminBase.html.twig' %}

{% block body %}
  {% include '/Navbar/adminNavbar.html.twig' %}

  <div id="wrapper">
    {% include '/Sidebar/adminSidebar.html.twig' %}
    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>

        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Books</div>
          <div class="card-body">
            <button type="button" class="btn btn-outline-danger mb-3 disabled" style="width:5%" id="bremove" name="books">Remove</button>
            <button type="button" class="btn btn-outline-info mb-3 disabled" style="width:5%" id="bedit" name="books">Edit</button>
            <table class="table table-bordered " id="tabela" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Authors</th>
                  <th>Publisher</th>
                  <th>Edition</th>
                </tr>
              </thead>

              <tbody>
                {% for book in books %}
                  <tr id="{{ book.bookId }}">
                    <td>{{ book.bookName}}</td>
                    <td>{{ book.author}}</td>
                    <td>{{ book.publisher}}</td>
                    <td>{{ book.edition}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Books App 2018</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ path('logout') }}">Logout</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

src/AppBundle/Resources/views/Admin/index.html.twig
{% extends 'adminBase.html.twig' %}

{% block body %}
  {% include '/Navbar/adminNavbar.html.twig' %}

  <div id="wrapper">
    {% include '/Sidebar/adminSidebar.html.twig' %}
    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>


      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Books App 2018</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ path('logout') }}">Logout</a>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

{% block javascripts %}

{% endblock %}

src/AppBundle/Resources/views/Admin/publishers.html.twig
{% extends 'adminBase.html.twig' %}

{% block body %}
  {% include '/Navbar/adminNavbar.html.twig' %}

  <div id="wrapper">
    {% include '/Sidebar/adminSidebar.html.twig' %}
    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>

        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Publishers</div>
          <div class="card-body">
            <button type="button" class="btn btn-outline-danger mb-3 disabled" style="width:5%" id="bremove" name="publishers">Remove</button>
            <button type="button" class="btn btn-outline-info mb-3 disabled" style="width:5%" id="bedit" name="publishers">Edit</button>
            <table class="table table-bordered" id="tabela" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Publisher Name</th>
                  <th>Country</th>
                </tr>
              </thead>

              <tbody>
                {% for publisher in publishers %}
                  <tr id="{{ publisher.publisherId }}">
                    <td>{{ publisher.publisherName}}</td>
                    <td>{{ publisher.country}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

        </div>

      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Books App 2018</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ path('logout') }}">Logout</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}